### ISSUE TITLE
xcframework issue: arm64 slice in intel version of framework

### ISSUE THREAD

**Issue by salling** [KatalysatorAB/glimr-ios-lite#3]
The xcframework does not seem to be configured correctly. The arm slices should be in *one* of the embedded frameworks, the intel slices in the other. I'm not sure how it's built, but `lipo` shows the problem:

➜  lipo -info …/glimr-ios-lite/GLGeoRealtime.xcframework/ios-arm64_i386_x86_64-simulator/GLGeoRealtime.framework/GLGeoRealtime 
Architectures in the fat file: …/glimr-ios-lite/GLGeoRealtime.xcframework/ios-arm64_i386_x86_64-simulator/GLGeoRealtime.framework/GLGeoRealtime are: i386 x86_64 arm64

**Comment by svenroed** [comment]
thanks @salling for this one. you are absolutely right. during the development we noticed a couple of issues with .xcframework so we reverted to the old style of building the framework but we didn't remove this broken xcframework which probably cause some confusion now. Sorry for that, we will tackle the xcframework again soon. 

I keep this ticket open until it's resolved.
